# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-alpine

# Install build dependencies
RUN apk add --no-cache build-base

# Upgrade pip and install uv
RUN pip install --upgrade pip
RUN pip install uv

# Copy application code
COPY . /app
WORKDIR /app

# Build the package using uv
RUN uv sync && uv build

# Expose any necessary port if needed (uv might not require it for MCP over stdio)

# Command to run the MCP server
CMD ["uv", "--directory", ".", "run", "spotify-mcp"]
